"""Initial migration

Revision ID: 023a1bf8e3ec
Revises: 
Create Date: 2025-04-08 14:52:57.262470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023a1bf8e3ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Creates initial tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=True),
    sa.Column('demographics', sa.JSON(), nullable=False),
    sa.Column('behavioral_traits', sa.JSON(), nullable=False),
    sa.Column('beliefs', sa.JSON(), nullable=False),
    sa.Column('short_term_memory', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_agent_id', sa.UUID(), nullable=False),
    sa.Column('target_agent_id', sa.UUID(), nullable=False),
    sa.Column('influence_factor', sa.Float(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_connections_id'), 'agent_connections', ['id'], unique=False)
    op.create_index(op.f('ix_agent_connections_source_agent_id'), 'agent_connections', ['source_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_connections_target_agent_id'), 'agent_connections', ['target_agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops initial tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_connections_target_agent_id'), table_name='agent_connections')
    op.drop_index(op.f('ix_agent_connections_source_agent_id'), table_name='agent_connections')
    op.drop_index(op.f('ix_agent_connections_id'), table_name='agent_connections')
    op.drop_table('agent_connections')
    op.drop_table('agents')
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
