"""Add server default to Simulation.updated_at

Revision ID: 0590ebacb1eb
Revises: e8f3d20d1fc0
Create Date: 2025-04-08 15:07:49.424780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0590ebacb1eb'
down_revision: Union[str, None] = 'e8f3d20d1fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
