"""Add cascades for agent deletion

Revision ID: 60603405a0f9
Revises: 9428ce1f007e
Create Date: 2025-04-08 16:15:13.990373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60603405a0f9'
down_revision: Union[str, None] = '9428ce1f007e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_connections_target_agent_id_fkey', 'agent_connections', type_='foreignkey')
    op.drop_constraint('agent_connections_source_agent_id_fkey', 'agent_connections', type_='foreignkey')
    op.create_foreign_key(None, 'agent_connections', 'agents', ['source_agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_connections', 'agents', ['target_agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_connections', type_='foreignkey')
    op.drop_constraint(None, 'agent_connections', type_='foreignkey')
    op.create_foreign_key('agent_connections_source_agent_id_fkey', 'agent_connections', 'agents', ['source_agent_id'], ['id'])
    op.create_foreign_key('agent_connections_target_agent_id_fkey', 'agent_connections', 'agents', ['target_agent_id'], ['id'])
    # ### end Alembic commands ###
