"""Add metric_snapshots table

Revision ID: 9428ce1f007e
Revises: d6afcaf61d22
Create Date: 2025-04-08 16:09:07.586028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9428ce1f007e'
down_revision: Union[str, None] = 'd6afcaf61d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('gini_coefficient', sa.Float(), nullable=True),
    sa.Column('belief_variance', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_simulation_id'), 'metric_snapshots', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_tick'), 'metric_snapshots', ['tick'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_tick'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_simulation_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
