"""Add agent_long_term_memories table

Revision ID: d6afcaf61d22
Revises: e8d1d1a3d5ca
Create Date: 2025-04-08 15:42:05.726558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd6afcaf61d22'
down_revision: Union[str, None] = 'e8d1d1a3d5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the dimension directly in the migration script
EMBEDDING_DIM = 768

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_long_term_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('memory_embedding', pgvector.sqlalchemy.Vector(EMBEDDING_DIM), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_long_term_memories_agent_id'), 'agent_long_term_memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_long_term_memories_id'), 'agent_long_term_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_long_term_memories_simulation_id'), 'agent_long_term_memories', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_long_term_memories_simulation_id'), table_name='agent_long_term_memories')
    op.drop_index(op.f('ix_agent_long_term_memories_id'), table_name='agent_long_term_memories')
    op.drop_index(op.f('ix_agent_long_term_memories_agent_id'), table_name='agent_long_term_memories')
    op.drop_table('agent_long_term_memories')
    # ### end Alembic commands ###
