"""Add simulations table and link to agents

Revision ID: e8f3d20d1fc0
Revises: 023a1bf8e3ec
Create Date: 2025-04-08 14:59:05.095033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f3d20d1fc0'
down_revision: Union[str, None] = '023a1bf8e3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('current_tick', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_name'), 'simulations', ['name'], unique=False)
    op.add_column('agents', sa.Column('simulation_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'agents', 'simulations', ['simulation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'simulation_id')
    op.drop_index(op.f('ix_simulations_name'), table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
